### PR TITLE
Replace blocking code in `poll_ready` with async code

### PR DESCRIPTION
**Pull request by paulgb**
Currently, `Inner::poll_ready` [loops](https://github.com/mechiru/google-authz/blob/master/src/service.rs#L72) while waiting for credentials. On a single-threaded executor (like Actix), this results in the program getting stuck in a loop using 100% of its CPU core, since the future it's waiting on is never scheduled.

This PR changes `poll_ready` so that it returns `Poll::Pending` unless a cached token is available when it is called.

### CODE REVIEW

**Comment by mechiru** [comment]
@paulgb 
Sorry for the late reply 😅
Thank you for your contribution and for pointing out the problem!
I did not add a fix to this pull request because I decided it would be better to fix the other crates as well and resolve this issue.
The same fix as suggested in the pull request was made in this commit(https://github.com/mechiru/google-authz/commit/4054331b06e34bec00640a7c6d25c9b002d174a1) .
Can you please confirm that the problem has been resolved?

**Comment by paulgb** [comment]
Thanks @mechiru, I appreciate all your work on this.

One comment on your approach, the type:

    Pin<Box<dyn Future<Output = token::Result<Token>> + Send + 'static>>,

is not `Sync`, because the future itself is not `Sync`. This bubbles all the way up to make `AddAuthorization` not sync. A result of this is that a service wrapped by `AddAuthorization` can't be used by a connection pool.

[The approach I took to this](https://github.com/mechiru/google-authz/pull/1/commits/a696a5d62ee67ec7739f99cce91c909c9c4cde93#diff-5c6f87176b7f64fbbeabbc31f5ad377edc268ebeb231eb55ee31c14ec3834f23R101) was to wrap it all in a (std) `Mutex`. Mutex is `impl Sync for Mutex<T>` where `T: Send`, so wrapping it this way results in `AddAuthorization` being `Sync`. This avoids two threads trying to progress the inner future at once.

The justification for a sync mutex instead of an async one is that it is not held over an `await` block and is never used in a blocking manner, only through `try_lock`.

If you like that approach, I would be happy to submit another PR on top of your latest commits applying it.

**Comment by mechiru** [comment]
@paulgb 
Thanks for your review. 
The code you suggested is great!

I recognize the problem and suggest a way to solve it using `unsafe impl`.
Because `State` is a property of `RwLock<Inner>` and access to `State.Fetching` is exclusively controlled by using `RwLock.write`.

branch: https://github.com/mechiru/google-authz/tree/fix/add-sync
commit: https://github.com/mechiru/google-authz/commit/243dc2f734fb73dc37ca512a228ced57cd98ecfc

I want to make the code better, so I will consider all possibilities, not just the way I suggested.
What do you think?

**Comment by paulgb** [comment]
That approach works too. I would suggest that it should be:

    unsafe impl Sync for Inner {}

rather than for `State`, since `State` on its own is *not* a sync type. It doesn't matter so much because `State` is not a public type, but it might make it easier to avoid concurrency bugs down the road if the types match the concurrency semantics.

Also, it's up to you, but I'd consider limiting the `unsafe` to a tighter scope using a zero-cost type, like this:

```rust
/// RefGuard wraps a `Send` type to make it `Sync`, by ensuring that it is only
/// ever accessed through a &mut pointer.
struct RefGuard<T: Send>(T);

impl<T: Send> RefGuard<T> {
    pub fn new(value: T) -> Self {
        RefGuard(value)
    }

    pub fn get_mut(&mut self) -> &mut T {
        &mut self.0
    }
}

unsafe impl<T: Send> Sync for RefGuard<T> {}
```

And then using it around `fut` in `State`:

```rust
        fut: RefGuard<Pin<Box<dyn Future<Output = token::Result<Token>> + Send + 'static>>>,
```

That way, `State` really will be `Sync` and the compiler will detect that automatically.

**Comment by paulgb** [comment]
Here's a branch with this approach implemented: https://github.com/paulgb/google-authz/tree/fix/add-sync

**Comment by mechiru** [comment]
> That approach works too. I would suggest that it should be:
> 
> ```
> unsafe impl Sync for Inner {}
> ```

I prefer this one too 😁

> Here's a branch with this approach implemented: https://github.com/paulgb/google-authz/tree/fix/add-sync

@paulgb 
This approach is very cool.
Can you create a pull request to this repository?

**Comment by mechiru** [comment]
@paulgb Thanks. Version v0.0.2 has been released.

**Pull request closed without merging**
